[project]
name = "auto_uploader_bot"
version = "1.0.0"
description = "Telegram bot to upload files and create deep links"
requires-python = ">=3.10"
dependencies = [
  "python-telegram-bot==20.8"
]
